In [1]:
import os

import sys
import time

import init_load_board as ib 
import init_simple_mdp as imdp

import function_board as fb 
import function_tool as ft

import pandas as pd

import numpy as np
np.set_printoptions(precision=4)
np.set_printoptions(linewidth=300)
np.set_printoptions(threshold=300)

import torch
torch.set_printoptions(precision=4)
torch.set_printoptions(linewidth=300)
torch.set_printoptions(threshold=300)

import helpers as h 

#%%
data_parameter_dir = fb.data_parameter_dir
result_dir = './result'  

#os.chdir('darts-thesis')


In [2]:
## Solve for Single Case

player_num = 10 
epsilon = 1
tokens = 9
name_pa = 'player{}'.format(player_num)

[aiming_grid, prob_grid_normalscore_nt, prob_grid_singlescore_nt, prob_grid_doublescore_nt, prob_grid_triplescore_nt, prob_grid_bullscore_nt] = h.load_aiming_grid(name_pa, epsilon=epsilon, data_parameter_dir=data_parameter_dir, grid_version='custom_no_tokens')
[aiming_grid, prob_grid_normalscore_t, prob_grid_singlescore_t, prob_grid_doublescore_t, prob_grid_triplescore_t, prob_grid_bullscore_t] = h.load_aiming_grid('t', data_parameter_dir=data_parameter_dir, grid_version='custom_tokens')

prob_grid_doublescore_dic = None
prob_grid_doublescore_dic_t = None

result_dic = h.solve_dp_turn_tokens(tokens, aiming_grid, prob_grid_normalscore_nt, prob_grid_singlescore_nt, prob_grid_doublescore_nt, prob_grid_triplescore_nt, prob_grid_bullscore_nt,prob_grid_normalscore_t, prob_grid_singlescore_t, prob_grid_doublescore_t, prob_grid_triplescore_t, prob_grid_bullscore_t)


# print('------------------------------------------------------------------')
# print('Optimal Values: ')
# print(result_dic['optimal_value_dic'])
# print('------------------------------------------------------------------')
# print('Optimal Policy}: ')
# print(result_dic['optimal_action_index_dic'])

In [3]:
## Solve for Single Case

player_num = 10 
epsilon = 1
tokens = 9
name_pa = 'player{}'.format(player_num)

[aiming_grid, prob_grid_normalscore_nt, prob_grid_singlescore_nt, prob_grid_doublescore_nt, prob_grid_triplescore_nt, prob_grid_bullscore_nt] = h.load_aiming_grid(name_pa, epsilon=epsilon, data_parameter_dir=data_parameter_dir, grid_version='custom_no_tokens')
[aiming_grid, prob_grid_normalscore_t, prob_grid_singlescore_t, prob_grid_doublescore_t, prob_grid_triplescore_t, prob_grid_bullscore_t] = h.load_aiming_grid('t', data_parameter_dir=data_parameter_dir, grid_version='custom_tokens')

prob_grid_doublescore_dic = None
prob_grid_doublescore_dic_t = None

result_dic = h.solve_dp_turn_tokens(tokens, aiming_grid, prob_grid_normalscore_nt, prob_grid_singlescore_nt, prob_grid_doublescore_nt, prob_grid_triplescore_nt, prob_grid_bullscore_nt,prob_grid_normalscore_t, prob_grid_singlescore_t, prob_grid_doublescore_t, prob_grid_triplescore_t, prob_grid_bullscore_t)


# print('------------------------------------------------------------------')
# print('Optimal Values: ')
# print(result_dic['optimal_value_dic'])
# print('------------------------------------------------------------------')
# print('Optimal Policy}: ')
# print(result_dic['optimal_action_index_dic'])

FileNotFoundError: [Errno 2] No such file or directory: './data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e1_gaussin_prob_grid_custom_no_tokens.pkl'

In [6]:
def create_result_dataframes(result_dic,epsilon):
    
    col_names = ['epsilon','tokens','score','remaining_throws','score_gained','optimal_value','optimal_policy']
    df_list = []

    for s in  result_dic['optimal_value_dic'].keys():
        for rt in range(1,4):
            for t in range(0,result_dic['optimal_value_dic'][s][rt].shape[0]):
                for u in range(0,result_dic['optimal_value_dic'][s][rt].shape[1]):
                    optimal_value = result_dic['optimal_value_dic'][s][rt][t][u]
                    if optimal_value == 1000:
                        continue
                    else:
                        optimal_policy = result_dic['optimal_action_index_dic'][s][rt][t][u]
                        df_list.append([epsilon,t,s,rt,u,optimal_value,optimal_policy])

    df = pd.DataFrame(df_list,columns=col_names)
        
    return df 


In [7]:
# Run Experiments
player_num = 10 
epsilon_list = [1,2,3,4,5,6,7,8,9,10,12,14,16,18,20,32,64,128,25,50,100]
name_pa = 'player{}'.format(player_num)

col_names = ['epsilon','tokens','score','remaining_throws','score_gained','optimal_value','optimal_policy']
df = pd.DataFrame(columns=col_names)

[aiming_grid, prob_grid_normalscore_t, prob_grid_singlescore_t, prob_grid_doublescore_t, prob_grid_triplescore_t, prob_grid_bullscore_t] = h.load_aiming_grid('t', data_parameter_dir=data_parameter_dir, grid_version='custom_tokens')

for epsilon in epsilon_list:
    [aiming_grid, prob_grid_normalscore_nt, prob_grid_singlescore_nt, prob_grid_doublescore_nt, prob_grid_triplescore_nt, prob_grid_bullscore_nt] = h.load_aiming_grid(name_pa, epsilon=epsilon, data_parameter_dir=data_parameter_dir, grid_version='custom_no_tokens')
    result_dic = h.solve_dp_turn_tokens(tokens, aiming_grid, prob_grid_normalscore_nt, prob_grid_singlescore_nt, prob_grid_doublescore_nt, prob_grid_triplescore_nt, prob_grid_bullscore_nt,prob_grid_normalscore_t, prob_grid_singlescore_t, prob_grid_doublescore_t, prob_grid_triplescore_t, prob_grid_bullscore_t)
    df = pd.concat([df,create_result_dataframes(result_dic,epsilon)])
    df = df.reset_index().drop(['index'],axis=1)

load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_tokens/t_gaussin_prob_grid_custom_tokens.pkl
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e1_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: overflow encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: overflow encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1190: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[:,score_gained_index] = num_turns_array[:,score_gained_index] / prob_notbust_dic_nt[score_max]
/Users/rachael/Desktop/darts-thesis/helpers.py:1190: RuntimeWarning: overflow encountered in divide
  num_turns_array[:,score_gained_index] = num_turns_array[:,score_gained_index] / prob_no

solve prob_policy_transit in 2.869497776031494 seconds
solve dp_turn_policyiter in 26.906985998153687 seconds
[[0.     0.     1.8856 ... 5.5944 5.5758 5.6116]
 [0.     0.     1.     ... 4.9684 4.9631 4.9765]
 [0.     0.     1.     ... 4.7444 4.7403 4.7516]
 ...
 [0.     0.     1.     ... 3.8073 3.8027 3.8082]
 [0.     0.     1.     ... 3.5561 3.5447 3.5554]
 [0.     0.     1.     ... 3.     3.     3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e2_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 3.8414149284362793 seconds
solve dp_turn_policyiter in 27.336097955703735 seconds
[[0.     0.     2.5371 ... 7.405  7.4122 7.4278]
 [0.     0.     1.     ... 6.2669 6.2766 6.2896]
 [0.     0.     1.     ... 5.8664 5.8755 5.8889]
 ...
 [0.     0.     1.     ... 3.9983 3.9972 4.0014]
 [0.     0.     1.     ... 3.7246 3.6864 3.6893]
 [0.     0.     1.     ... 3.     3.     3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e3_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 4.479038953781128 seconds
solve dp_turn_policyiter in 33.744544982910156 seconds
[[0.     0.     3.0946 ... 8.938  8.9526 8.9673]
 [0.     0.     1.     ... 7.3119 7.3263 7.3409]
 [0.     0.     1.     ... 6.7576 6.772  6.7866]
 ...
 [0.     0.     1.     ... 4.1578 4.1653 4.1713]
 [0.     0.     1.     ... 3.7995 3.7591 3.7597]
 [0.     0.     1.     ... 3.     3.     3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e4_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 4.9212751388549805 seconds
solve dp_turn_policyiter in 47.08125185966492 seconds
[[ 0.      0.      3.6299 ... 10.1945 10.2106 10.227 ]
 [ 0.      0.      1.     ...  8.0901  8.106   8.1224]
 [ 0.      0.      1.     ...  7.4217  7.4375  7.4541]
 ...
 [ 0.      0.      1.     ...  4.2948  4.3036  4.3148]
 [ 0.      0.      1.     ...  3.8377  3.799   3.8057]
 [ 0.      0.      1.     ...  3.      3.      3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e5_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 4.862528085708618 seconds
solve dp_turn_policyiter in 36.42272114753723 seconds
[[ 0.      0.      4.1579 ... 11.2985 11.3159 11.3335]
 [ 0.      0.      1.     ...  8.7127  8.7301  8.7477]
 [ 0.      0.      1.     ...  7.9508  7.9681  7.9858]
 ...
 [ 0.      0.      1.     ...  4.4068  4.4171  4.4321]
 [ 0.      0.      1.     ...  3.8621  3.8266  3.8402]
 [ 0.      0.      1.     ...  3.      3.      3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e6_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 5.097880840301514 seconds
solve dp_turn_policyiter in 37.2662079334259 seconds
[[ 0.      0.      4.6828 ... 12.2911 12.3097 12.3283]
 [ 0.      0.      1.     ...  9.2161  9.2347  9.2533]
 [ 0.      0.      1.     ...  8.3775  8.396   8.4146]
 ...
 [ 0.      0.      1.     ...  4.4992  4.5108  4.5278]
 [ 0.      0.      1.     ...  3.8823  3.8475  3.8686]
 [ 0.      0.      1.     ...  3.      3.      3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e7_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 5.168461799621582 seconds
solve dp_turn_policyiter in 32.59128499031067 seconds
[[ 0.      0.      5.2061 ... 13.1942 13.2137 13.2331]
 [ 0.      0.      1.     ...  9.6263  9.6458  9.6652]
 [ 0.      0.      1.     ...  8.7243  8.7437  8.7632]
 ...
 [ 0.      0.      1.     ...  4.5744  4.5876  4.6058]
 [ 0.      0.      1.     ...  3.9002  3.8646  3.8942]
 [ 0.      0.      1.     ...  3.      3.      3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e8_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 5.235445976257324 seconds
solve dp_turn_policyiter in 33.656079053878784 seconds
[[ 0.      0.      5.7282 ... 14.0264 14.0466 14.0667]
 [ 0.      0.      1.     ...  9.9646  9.9849 10.005 ]
 [ 0.      0.      1.     ...  9.0095  9.0297  9.0499]
 ...
 [ 0.      0.      1.     ...  4.6378  4.6513  4.671 ]
 [ 0.      0.      1.     ...  3.9091  3.8792  3.918 ]
 [ 0.      0.      1.     ...  3.      3.      3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e9_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 5.301178693771362 seconds
solve dp_turn_policyiter in 33.499086141586304 seconds
[[ 0.      0.      6.2493 ... 14.8038 14.8246 14.8454]
 [ 0.      0.      1.     ... 10.2476 10.2684 10.2892]
 [ 0.      0.      1.     ...  9.2476  9.2684  9.2892]
 ...
 [ 0.      0.      1.     ...  4.693   4.7073  4.7282]
 [ 0.      0.      1.     ...  3.9173  3.8924  3.9293]
 [ 0.      0.      1.     ...  3.      3.      3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e10_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 5.369704008102417 seconds
solve dp_turn_policyiter in 34.03449106216431 seconds
[[ 0.      0.      6.7696 ... 15.5402 15.5615 15.5828]
 [ 0.      0.      1.     ... 10.4873 10.5086 10.5299]
 [ 0.      0.      1.     ...  9.449   9.4703  9.4916]
 ...
 [ 0.      0.      1.     ...  4.7412  4.7568  4.7789]
 [ 0.      0.      1.     ...  3.9247  3.9046  3.9398]
 [ 0.      0.      1.     ...  3.      3.      3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e12_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 5.396705150604248 seconds
solve dp_turn_policyiter in 34.05711913108826 seconds
[[ 0.      0.      7.8076 ... 16.9251 16.9471 16.9692]
 [ 0.      0.      1.     ... 10.8695 10.8916 10.9137]
 [ 0.      0.      1.     ...  9.7688  9.7908  9.8129]
 ...
 [ 0.      0.      1.     ...  4.8231  4.8412  4.8641]
 [ 0.      0.      1.     ...  3.939   3.9215  3.9598]
 [ 0.      0.      1.     ...  3.      3.      3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e14_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 5.480510950088501 seconds
solve dp_turn_policyiter in 34.16329908370972 seconds
[[ 0.      0.      8.8425 ... 18.2268 18.2494 18.272 ]
 [ 0.      0.      1.     ... 11.1564 11.1791 11.2017]
 [ 0.      0.      1.     ... 10.0082 10.0308 10.0534]
 ...
 [ 0.      0.      1.     ...  4.8902  4.9096  4.9329]
 [ 0.      0.      1.     ...  3.9544  3.9374  3.9782]
 [ 0.      0.      1.     ...  3.      3.      3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e16_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 5.520420074462891 seconds
solve dp_turn_policyiter in 34.20482683181763 seconds
[[ 0.      0.      9.8744 ... 19.4836 19.5067 19.5297]
 [ 0.      0.      1.     ... 11.3908 11.4138 11.4369]
 [ 0.      0.      1.     ... 10.2015 10.2246 10.2477]
 ...
 [ 0.      0.      1.     ...  4.9452  4.9652  4.9892]
 [ 0.      0.      1.     ...  3.9693  3.9533  3.9954]
 [ 0.      0.      1.     ...  3.      3.      3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e18_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 5.548665285110474 seconds
solve dp_turn_policyiter in 34.54860067367554 seconds
[[ 0.      0.     10.9033 ... 20.7137 20.7372 20.7607]
 [ 0.      0.      1.     ... 11.5953 11.6187 11.6422]
 [ 0.      0.      1.     ... 10.3692 10.3926 10.4161]
 ...
 [ 0.      0.      1.     ...  4.9924  5.0134  5.0379]
 [ 0.      0.      1.     ...  3.9836  3.969   4.0118]
 [ 0.      0.      1.     ...  3.      3.      3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e20_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 5.578678131103516 seconds
solve dp_turn_policyiter in 34.18764400482178 seconds
[[ 0.      0.     11.9292 ... 21.9282 21.952  21.9758]
 [ 0.      0.      1.     ... 11.7824 11.8062 11.8301]
 [ 0.      0.      1.     ... 10.523  10.5468 10.5707]
 ...
 [ 0.      0.      1.     ...  5.036   5.0577  5.0827]
 [ 0.      0.      1.     ...  3.9978  3.9847  4.0273]
 [ 0.      0.      1.     ...  3.      3.      3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e32_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 5.617704153060913 seconds
solve dp_turn_policyiter in 34.44908690452576 seconds
[[ 0.      0.     18.0248 ... 29.0768 29.1025 29.1283]
 [ 0.      0.      1.     ... 12.7483 12.7741 12.7999]
 [ 0.      0.      1.     ... 11.3189 11.3447 11.3705]
 ...
 [ 0.      0.      1.     ...  5.2492  5.2741  5.301 ]
 [ 0.      0.      1.     ...  4.0666  4.0665  4.1058]
 [ 0.      0.      1.     ...  3.      3.      3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e64_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 5.620567083358765 seconds
solve dp_turn_policyiter in 34.81292676925659 seconds
[[ 0.      0.     33.7957 ... 46.6229 46.651  46.679 ]
 [ 0.      0.      1.     ... 13.9882 14.0162 14.0443]
 [ 0.      0.      1.     ... 12.2849 12.3129 12.341 ]
 ...
 [ 0.      0.      1.     ...  5.5345  5.5625  5.591 ]
 [ 0.      0.      1.     ...  4.1891  4.2016  4.2428]
 [ 0.      0.      1.     ...  3.      3.      3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e128_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 5.6096413135528564 seconds
solve dp_turn_policyiter in 34.76471400260925 seconds
[[ 0.      0.     63.3393 ... 80.2283 80.2605 80.2926]
 [ 0.      0.      1.     ... 16.1877 16.2199 16.252 ]
 [ 0.      0.      1.     ... 13.9846 14.0167 14.0489]
 ...
 [ 0.      0.      1.     ...  6.0106  6.0427  6.0751]
 [ 0.      0.      1.     ...  4.4165  4.4348  4.4822]
 [ 0.      0.      1.     ...  3.      3.      3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e25_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 5.6059770584106445 seconds
solve dp_turn_policyiter in 34.310730934143066 seconds
[[ 0.      0.     14.4813 ... 24.9292 24.9538 24.9785]
 [ 0.      0.      1.     ... 12.2081 12.2328 12.2574]
 [ 0.      0.      1.     ... 10.8736 10.8983 10.923 ]
 ...
 [ 0.      0.      1.     ...  5.1335  5.1567  5.1826]
 [ 0.      0.      1.     ...  4.0278  4.0233  4.0635]
 [ 0.      0.      1.     ...  3.      3.      3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e50_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 5.618575096130371 seconds
solve dp_turn_policyiter in 34.18096303939819 seconds
[[ 0.      0.     26.9819 ... 39.0309 39.058  39.0852]
 [ 0.      0.      1.     ... 13.4965 13.5236 13.5508]
 [ 0.      0.      1.     ... 11.9069 11.9341 11.9612]
 ...
 [ 0.      0.      1.     ...  5.4275  5.4547  5.4822]
 [ 0.      0.      1.     ...  4.1427  4.154   4.1909]
 [ 0.      0.      1.     ...  3.      3.      3.    ]]
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e100_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1183: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[imdp.throw_num:,score_gained_index] = num_turns_array[imdp.throw_num:,score_gained_index] / prob_notbust_dic_t[score_max][imdp.throw_num:]
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/helpers.py:1210: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 5.605164051055908 seconds
solve dp_turn_policyiter in 34.197933197021484 seconds
[[ 0.      0.     50.7214 ... 65.6365 65.6665 65.6966]
 [ 0.      0.      1.     ... 15.0957 15.1257 15.1558]
 [ 0.      0.      1.     ... 13.1267 13.1567 13.1868]
 ...
 [ 0.      0.      1.     ...  5.7803  5.8103  5.8408]
 [ 0.      0.      1.     ...  4.3103  4.3256  4.371 ]
 [ 0.      0.      1.     ...  3.      3.      3.    ]]


In [8]:
# Save to File
df.to_csv('player10_results.csv')
df

epsilon tokens score remaining_throws score_gained  optimal_value  \
0              1      0     2                1            0       2.232611   
1              1      1     2                1            0       1.000000   
2              1      2     2                1            0       1.000000   
3              1      3     2                1            0       1.000000   
4              1      4     2                1            0       1.000000   
...          ...    ...   ...              ...          ...            ...   
14947585     100      5   501                3            0       8.779258   
14947586     100      6   501                3            0       7.310111   
14947587     100      7   501                3            0       5.840758   
14947588     100      8   501                3            0       4.370963   
14947589     100      9   501                3            0       3.000000   

         optimal_policy  
0                    55  
1                   752  
2                   752  
3                   752  
4                   752  
...                 ...  
14947585            728  
14947586            728  
14947587            728  
14947588            728  
14947589            750  

[14947590 rows x 7 columns]

In [2]:
epsilon_list = [1,2,3,4,5,6,7,8,9]

player_num = 10 
name_pa = 'player{}'.format(player_num)

for epsilon in epsilon_list:
    h.solve_singlegame_token(name_pa, epsilon, tokens=9, data_parameter_dir=fb.data_parameter_dir, result_dir='result', postfix='')


load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e1_gaussin_prob_grid_custom_no_tokens.pkl
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_tokens/t_gaussin_prob_grid_custom_tokens.pkl
runing solve_dp_turn with credits


/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:719: RuntimeWarning: overflow encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:757: RuntimeWarning: overflow encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:1190: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[:,score_gained_index] = num_turns_array[:,score_gained_index] / prob_notbust_dic_nt[score_max]
/Users/rachael/Desktop/darts-thesis/helpers.py:1190: RuntimeWarning: overflow encountered in divide
  num_turns_array[:,score_gained_index] = num_turns_array[:,score_gained_index] / prob_no

solve prob_policy_transit in 2.8826680183410645 seconds
solve dp_turn_policyiter in 26.20723581314087 seconds
[[0.     0.     1.8856 ... 5.5944 5.5758 5.6116]
 [0.     0.     1.     ... 4.9684 4.9631 4.9765]
 [0.     0.     1.     ... 4.7444 4.7403 4.7516]
 ...
 [0.     0.     1.     ... 3.8073 3.8027 3.8082]
 [0.     0.     1.     ... 3.5561 3.5447 3.5554]
 [0.     0.     1.     ... 3.     3.     3.    ]]
dump_pickle to result/singlegame_player10_e1_turn_tokens.pkl
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e2_gaussin_prob_grid_custom_no_tokens.pkl
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_tokens/t_gaussin_prob_grid_custom_tokens.pkl
runing solve_dp_turn with credits
solve prob_policy_transit in 3.8183376789093018 seconds
solve dp_turn_policyiter in 30.14551615715027 seconds
[[0.     0.     2.5371 ... 7.405  7.4122 7.4278]
 [0.     0.     1.     ... 6.2669 6.2766 6.2896]
 [0.     0.     1.     ... 5.8664 5.8755 5.8889]
 .

# *Master Runfile to Set Up Directory

In [2]:
epsilon_list = [1,2,3,4,5,6,7,8,9]
playerID_list = [10]

for epsilon in epsilon_list:
    h.evaluate_score_probability(playerID_list,epsilon=epsilon,f_density_grid_pixel_per_mm=0.5)

f_density_grid_num=171 f_density_grid_width=2.0

computing ./data_parameter/player_gaussin_fit/grid_full/e1_player10_gaussin_prob_grid.pkl
computation is done in 89.13993549346924 seconds
dump_pickle to ./data_parameter/player_gaussin_fit/grid_full/e1_player10_gaussin_prob_grid.pkl
f_density_grid_num=171 f_density_grid_width=2.0

computing ./data_parameter/player_gaussin_fit/grid_full/e2_player10_gaussin_prob_grid.pkl
computation is done in 78.58092546463013 seconds
dump_pickle to ./data_parameter/player_gaussin_fit/grid_full/e2_player10_gaussin_prob_grid.pkl
f_density_grid_num=171 f_density_grid_width=2.0

computing ./data_parameter/player_gaussin_fit/grid_full/e3_player10_gaussin_prob_grid.pkl
computation is done in 77.67733192443848 seconds
dump_pickle to ./data_parameter/player_gaussin_fit/grid_full/e3_player10_gaussin_prob_grid.pkl
f_density_grid_num=171 f_density_grid_width=2.0

computing ./data_parameter/player_gaussin_fit/grid_full/e4_player10_gaussin_prob_grid.pkl
computation 

In [3]:
h.save_aiming_grid_custom_tokens()

for epsilon in epsilon_list:
    h.save_aiming_grid_custom_no_tokens(playerID_list,epsilon=epsilon)

generate and save action set grid_version=custom_tokens
dump_pickle to ./data_parameter/player_gaussin_fit/grid_custom_tokens/t_gaussin_prob_grid_custom_tokens.pkl

generate and save action set grid_version=custom_no_tokens
load_pickle from ./data_parameter/player_gaussin_fit/grid_full/e1_player10_gaussin_prob_grid.pkl
dump_pickle to ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e1_gaussin_prob_grid_custom_no_tokens.pkl

generate and save action set grid_version=custom_no_tokens
load_pickle from ./data_parameter/player_gaussin_fit/grid_full/e2_player10_gaussin_prob_grid.pkl
dump_pickle to ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e2_gaussin_prob_grid_custom_no_tokens.pkl

generate and save action set grid_version=custom_no_tokens
load_pickle from ./data_parameter/player_gaussin_fit/grid_full/e3_player10_gaussin_prob_grid.pkl
dump_pickle to ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e3_gaussin_prob_grid_custom_no_toke

In [3]:
data_parameter_dir = fb.data_parameter_dir
result_dir = './result'

player_num = 10
name_pa = 'player{}'.format(player_num)

epsilon_list = [1,2,3,4,5,6,7,8,9]

for epsilon in epsilon_list:
    h.solve_singlegame_token(name_pa, epsilon, tokens=9, data_parameter_dir=fb.data_parameter_dir, result_dir='result', postfix='')


load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e1_gaussin_prob_grid_custom_no_tokens.pkl
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_tokens/t_gaussin_prob_grid_custom_tokens.pkl
runing solve_dp_turn with credits


C:\Users\Craig\PycharmProjects\darts-thesis\helpers.py:719: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
C:\Users\Craig\PycharmProjects\darts-thesis\helpers.py:719: RuntimeWarning: overflow encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
C:\Users\Craig\PycharmProjects\darts-thesis\helpers.py:757: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
C:\Users\Craig\PycharmProjects\darts-thesis\helpers.py:757: RuntimeWarning: overflow encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
C:\Users\Craig\PycharmProjects\darts-thesis\helpers.py:1176: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[:,score_gained_index] = num_turns_array[:,score_gained_index] / prob_notbust_dic_nt[score_max]
C:\Users\Craig\PycharmProjects\darts-thesis\helpers.py:1176: RuntimeWarning: overflow encountered in divide
  num_turns_array[:,score_gained_index] =

solve prob_policy_transit in 1.293320655822754 seconds
solve dp_turn_policyiter in 15.0060396194458 seconds
[[0.     0.     1.8856 ... 5.5944 5.5758 5.6116]
 [0.     0.     1.     ... 4.9684 4.9631 4.9765]
 [0.     0.     1.     ... 4.7444 4.7403 4.7516]
 ...
 [0.     0.     1.     ... 3.8073 3.8027 3.8082]
 [0.     0.     1.     ... 3.5561 3.5447 3.5554]
 [0.     0.     1.     ... 3.     3.     3.    ]]
dump_pickle to result/singlegame_player10_e1_turn_tokens.pkl
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e2_gaussin_prob_grid_custom_no_tokens.pkl
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_tokens/t_gaussin_prob_grid_custom_tokens.pkl
runing solve_dp_turn with credits
solve prob_policy_transit in 1.7004752159118652 seconds
solve dp_turn_policyiter in 15.256051063537598 seconds
[[0.     0.     2.5371 ... 7.405  7.4122 7.4278]
 [0.     0.     1.     ... 6.2669 6.2766 6.2896]
 [0.     0.     1.     ... 5.8664 5.8755 5.8889]
 ..