In [9]:
import os
import sys
import time

import init_load_board as ib 
import init_simple_mdp as imdp

import function_board as fb 
import function_tool as ft

import pandas as pd

import numpy as np
np.set_printoptions(precision=4)
np.set_printoptions(linewidth=300)
np.set_printoptions(threshold=300)

import torch
torch.set_printoptions(precision=4)
torch.set_printoptions(linewidth=300)
torch.set_printoptions(threshold=300)

import helpers as h 

#%%
data_parameter_dir = fb.data_parameter_dir
result_dir = './result'       



In [34]:
# playerID_list = [1,2,3]
playerID_list = [10]
epsilon_list = [8,9,10,20]

In [35]:
for epsilon in epsilon_list: 
    h.evaluate_score_probability(playerID_list,epsilon=epsilon,f_density_grid_pixel_per_mm=0.5)

f_density_grid_num=171 f_density_grid_width=2.0

computing ./data_parameter/player_gaussin_fit/grid_full/e8_player10_gaussin_prob_grid.pkl
computation is done in 302.7138648033142 seconds
dump_pickle to ./data_parameter/player_gaussin_fit/grid_full/e8_player10_gaussin_prob_grid.pkl
f_density_grid_num=171 f_density_grid_width=2.0

computing ./data_parameter/player_gaussin_fit/grid_full/e9_player10_gaussin_prob_grid.pkl
computation is done in 305.3214249610901 seconds
dump_pickle to ./data_parameter/player_gaussin_fit/grid_full/e9_player10_gaussin_prob_grid.pkl
f_density_grid_num=171 f_density_grid_width=2.0

computing ./data_parameter/player_gaussin_fit/grid_full/e10_player10_gaussin_prob_grid.pkl
computation is done in 310.0020477771759 seconds
dump_pickle to ./data_parameter/player_gaussin_fit/grid_full/e10_player10_gaussin_prob_grid.pkl
f_density_grid_num=171 f_density_grid_width=2.0

computing ./data_parameter/player_gaussin_fit/grid_full/e20_player10_gaussin_prob_grid.pkl
computati

In [ ]:
# Code to look at the probability grid

#####------------- Load the Probability Grid ---------------#####

# temp = h.load_prob_grid(playername_filename='player1',epsilon=1,data_parameter_dir=data_parameter_dir)

####------------------------ Output -------------------------####
# Probability grid contains a list of five objects
# 0 --> shape (341, 341, 61) for every point on the 341x341 grid, probability of hitting score 0 to 60 
# 1 --> shape (341, 341, 20) for every point on the 341x341 grid, probability of hitting single of index 0 to 20
# 2 --> shape (341, 341, 20) for every point on the 341x341 grid, probability of hitting double of index 0 to 20
# 3 --> shape (341, 341, 20) for every point on the 341x341 grid, probability of hitting triple of index 0 to 20
# 4 --> shape (341, 341, 2) for every point on the 341x341 grid, probability of hitting bullseye of index 0 (single) or 1 (double)

# temp[0].shape

In [36]:
h.save_aiming_grid_custom_tokens()

for epsilon in epsilon_list: 
    h.save_aiming_grid_custom_no_tokens(playerID_list,epsilon=epsilon)

generate and save action set grid_version=custom_tokens
dump_pickle to ./data_parameter/player_gaussin_fit/grid_custom_tokens/t_gaussin_prob_grid_custom_tokens.pkl

generate and save action set grid_version=custom_no_tokens
load_pickle from ./data_parameter/player_gaussin_fit/grid_full/e8_player10_gaussin_prob_grid.pkl
dump_pickle to ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e8_gaussin_prob_grid_custom_no_tokens.pkl

generate and save action set grid_version=custom_no_tokens
load_pickle from ./data_parameter/player_gaussin_fit/grid_full/e9_player10_gaussin_prob_grid.pkl
dump_pickle to ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e9_gaussin_prob_grid_custom_no_tokens.pkl

generate and save action set grid_version=custom_no_tokens
load_pickle from ./data_parameter/player_gaussin_fit/grid_full/e10_player10_gaussin_prob_grid.pkl
dump_pickle to ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e10_gaussin_prob_grid_custom_no_to

In [19]:
player_num = 10 
epsilon = 1
name_pa = 'player{}'.format(player_num)

[aiming_grid, prob_grid_normalscore_nt, prob_grid_singlescore_nt, prob_grid_doublescore_nt, prob_grid_triplescore_nt, prob_grid_bullscore_nt] = h.load_aiming_grid(name_pa, epsilon=epsilon, data_parameter_dir=data_parameter_dir, grid_version='custom_no_tokens')
[aiming_grid, prob_grid_normalscore_t, prob_grid_singlescore_t, prob_grid_doublescore_t, prob_grid_triplescore_t, prob_grid_bullscore_t] = h.load_aiming_grid('t', data_parameter_dir=data_parameter_dir, grid_version='custom_tokens')

prob_grid_doublescore_dic = None
prob_grid_doublescore_dic_t = None

[optimal_value, optimal_action_index] = h.solve_dp_noturn_tokens(aiming_grid, prob_grid_normalscore_nt, prob_grid_normalscore_t, tokens = 9, prob_grid_doublescore=prob_grid_doublescore_nt, prob_grid_bullscore=prob_grid_bullscore_nt, prob_grid_doublescore_dic=None, prob_grid_doublescore_t=prob_grid_doublescore_t, prob_grid_bullscore_t=prob_grid_bullscore_t, prob_grid_doublescore_dic_t=None)

print('------------------------------------------------------------------')
print('Optimal Values: ')
print(optimal_value)
print('------------------------------------------------------------------')
print('Optimal Policy}: ')
print(optimal_action_index)

load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e1_gaussin_prob_grid_custom_no_tokens.pkl
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_tokens/t_gaussin_prob_grid_custom_tokens.pkl
------------------------------------------------------------------
Optimal Values: 
[[ 0.      0.      2.8875 ... 15.796  15.7386 15.854 ]
 [ 0.      0.      1.     ... 14.031  14.0166 14.0347]
 [ 0.      0.      1.     ... 13.3518 13.3227 13.3554]
 ...
 [ 0.      0.      1.     ... 10.1522 10.1477 10.1718]
 [ 0.      0.      1.     ...  9.5936  9.5782  9.5959]
 [ 0.      0.      1.     ...  9.      9.      9.    ]]
------------------------------------------------------------------
Optimal Policy}: 
[[ -1  -1  55 ...  10  10  10]
 [ -1  -1 752 ...  10  10  10]
 [ -1  -1 752 ...  10  10  10]
 ...
 [ -1  -1 752 ...  10  10  10]
 [ -1  -1 752 ... 406 274 771]
 [ -1  -1 752 ... 750 750 750]]


In [20]:
player_num = 10 
epsilon = 2
name_pa = 'player{}'.format(player_num)

[aiming_grid, prob_grid_normalscore_nt, prob_grid_singlescore_nt, prob_grid_doublescore_nt, prob_grid_triplescore_nt, prob_grid_bullscore_nt] = h.load_aiming_grid(name_pa, epsilon=epsilon, data_parameter_dir=data_parameter_dir, grid_version='custom_no_tokens')
[aiming_grid, prob_grid_normalscore_t, prob_grid_singlescore_t, prob_grid_doublescore_t, prob_grid_triplescore_t, prob_grid_bullscore_t] = h.load_aiming_grid('t', data_parameter_dir=data_parameter_dir, grid_version='custom_tokens')

prob_grid_doublescore_dic = None
prob_grid_doublescore_dic_t = None

[optimal_value, optimal_action_index] = h.solve_dp_noturn_tokens(aiming_grid, prob_grid_normalscore_nt, prob_grid_normalscore_t, tokens = 9, prob_grid_doublescore=prob_grid_doublescore_nt, prob_grid_bullscore=prob_grid_bullscore_nt, prob_grid_doublescore_dic=None, prob_grid_doublescore_t=prob_grid_doublescore_t, prob_grid_bullscore_t=prob_grid_bullscore_t, prob_grid_doublescore_dic_t=None)

print('------------------------------------------------------------------')
print('Optimal Values: ')
print(optimal_value)
print('------------------------------------------------------------------')
print('Optimal Policy}: ')
print(optimal_action_index)

load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e2_gaussin_prob_grid_custom_no_tokens.pkl
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_tokens/t_gaussin_prob_grid_custom_tokens.pkl
------------------------------------------------------------------
Optimal Values: 
[[ 0.      0.      4.1576 ... 21.0713 21.0944 21.1402]
 [ 0.      0.      1.     ... 17.9593 17.9884 18.0261]
 [ 0.      0.      1.     ... 16.7237 16.7492 16.7889]
 ...
 [ 0.      0.      1.     ... 10.8805 10.8979 10.9422]
 [ 0.      0.      1.     ...  9.7987  9.7765  9.8601]
 [ 0.      0.      1.     ...  9.      9.      9.    ]]
------------------------------------------------------------------
Optimal Policy}: 
[[ -1  -1  43 ...  10  10  10]
 [ -1  -1 752 ...  10  10  10]
 [ -1  -1 752 ...  10  10  10]
 ...
 [ -1  -1 752 ... 406 771  10]
 [ -1  -1 752 ... 586 274 477]
 [ -1  -1 752 ... 750 750 750]]


In [16]:
player_num = 10 
epsilon = 4
name_pa = 'player{}'.format(player_num)

[aiming_grid, prob_grid_normalscore_nt, prob_grid_singlescore_nt, prob_grid_doublescore_nt, prob_grid_triplescore_nt, prob_grid_bullscore_nt] = h.load_aiming_grid(name_pa, epsilon=epsilon, data_parameter_dir=data_parameter_dir, grid_version='custom_no_tokens')
[aiming_grid, prob_grid_normalscore_t, prob_grid_singlescore_t, prob_grid_doublescore_t, prob_grid_triplescore_t, prob_grid_bullscore_t] = h.load_aiming_grid('t', data_parameter_dir=data_parameter_dir, grid_version='custom_tokens')

prob_grid_doublescore_dic = None
prob_grid_doublescore_dic_t = None

[optimal_value, optimal_action_index] = h.solve_dp_noturn_tokens(aiming_grid, prob_grid_normalscore_nt, prob_grid_normalscore_t, tokens = 9, prob_grid_doublescore=prob_grid_doublescore_nt, prob_grid_bullscore=prob_grid_bullscore_nt, prob_grid_doublescore_dic=None, prob_grid_doublescore_t=prob_grid_doublescore_t, prob_grid_bullscore_t=prob_grid_bullscore_t, prob_grid_doublescore_dic_t=None)

print('------------------------------------------------------------------')
print('Optimal Values: ')
print(optimal_value)
print('------------------------------------------------------------------')
print('Optimal Policy}: ')
print(optimal_action_index)

load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e4_gaussin_prob_grid_custom_no_tokens.pkl
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_tokens/t_gaussin_prob_grid_custom_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:506: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:544: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate


------------------------------------------------------------------
Optimal Values: 
[[ 0.      0.      6.1117 ... 28.9353 28.9832 29.0327]
 [ 0.      0.      1.     ... 23.4155 23.463  23.512 ]
 [ 0.      0.      1.     ... 21.4227 21.4694 21.5197]
 ...
 [ 0.      0.      1.     ... 11.8656 11.9348 11.9832]
 [ 0.      0.      1.     ... 10.0362 10.019  10.142 ]
 [ 0.      0.      1.     ...  9.      9.      9.    ]]
------------------------------------------------------------------
Optimal Policy}: 
[[ -1  -1  43 ... 406 406 406]
 [ -1  -1 752 ... 406 406 406]
 [ -1  -1 752 ... 406 406 406]
 ...
 [ -1  -1 752 ... 406 406 406]
 [ -1  -1 752 ... 586 598 771]
 [ -1  -1 752 ... 750 750 750]]


In [5]:
def create_result_dataframes(optimal_value,optimal_action_index):
    
    col_names = ['epsilon','tokens','score','optimal_value','optimal_policy']
    df_list = []
    
    for t in range(optimal_value.shape[0]):
        for s in range(optimal_value.shape[1]):
            df_list.append([epsilon,t,s,optimal_value[t][s],optimal_action_index[t][s]])

    df = pd.DataFrame(df_list,columns=col_names)
    
    return df 


In [13]:
player_num = 10 
epsilon_list = [1,2,3,4,5,6,7,8,9,10,20]
name_pa = 'player{}'.format(player_num)

col_names = ['epsilon','tokens','score','optimal_value','optimal_policy']
df = pd.DataFrame(columns=col_names)

[aiming_grid, prob_grid_normalscore_t, prob_grid_singlescore_t, prob_grid_doublescore_t, prob_grid_triplescore_t, prob_grid_bullscore_t] = h.load_aiming_grid('t', data_parameter_dir=data_parameter_dir, grid_version='custom_tokens')
prob_grid_doublescore_dic = None
prob_grid_doublescore_dic_t = None

for epsilon in epsilon_list:
    [aiming_grid, prob_grid_normalscore_nt, prob_grid_singlescore_nt, prob_grid_doublescore_nt, prob_grid_triplescore_nt, prob_grid_bullscore_nt] = h.load_aiming_grid(name_pa, epsilon=epsilon, data_parameter_dir=data_parameter_dir, grid_version='custom_no_tokens')
    [optimal_value, optimal_action_index] = h.solve_dp_noturn_tokens(aiming_grid, prob_grid_normalscore_nt, prob_grid_normalscore_t, tokens = 9, prob_grid_doublescore=prob_grid_doublescore_nt, prob_grid_bullscore=prob_grid_bullscore_nt, prob_grid_doublescore_dic=None, prob_grid_doublescore_t=prob_grid_doublescore_t, prob_grid_bullscore_t=prob_grid_bullscore_t, prob_grid_doublescore_dic_t=None)
    df = pd.concat([df,create_result_dataframes(optimal_value,optimal_action_index)])
    df = df.reset_index().drop(['index'],axis=1)

load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_tokens/t_gaussin_prob_grid_custom_tokens.pkl
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e1_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:506: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:506: RuntimeWarning: overflow encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:544: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:544: RuntimeWarning: overflow encountered in divide
  num_tothrow = num_tothrow / prob_otherstate


load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e2_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:506: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:544: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate


load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e3_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:506: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:544: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate


load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e4_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:506: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:544: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate


load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e5_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:506: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:544: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate


load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e6_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:506: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:544: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate


load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_e7_gaussin_prob_grid_custom_no_tokens.pkl


/Users/rachael/Desktop/darts-thesis/helpers.py:506: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/helpers.py:544: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate


In [14]:
df

epsilon tokens score  optimal_value optimal_policy
0           1      0     0       0.000000             -1
1           1      0     1       0.000000             -1
2           1      0     2       2.887532             55
3           1      0     3       3.897533             40
4           1      0     4       2.329057            295
...       ...    ...   ...            ...            ...
35135       7      9   497       9.000000            750
35136       7      9   498       9.000000            750
35137       7      9   499       9.000000            750
35138       7      9   500       9.000000            750
35139       7      9   501       9.000000            750

[35140 rows x 5 columns]