In [3]:
import init_load_board
exec(open('init_load_board.py').read())

import init_simple_mdp
exec(open('init_simple_mdp.py').read())

import numpy as np

import function_board as fb 
import function_tool as ft
import function_get_aiming_grid as fgag
exec(open('function_get_aiming_grid.py').read())

import evaluate_score_probability_with_error as esp
import function_solve_dp

#%%
data_parameter_dir = fb.data_parameter_dir
result_dir = './result'       


a_throw_list = []
a_token_list = []

for a in actions:
    a_throw_list.append(a)

for a in token_actions:
    a_token_list.append(a)


#esp.evaluate_score_probability([10,'t'],epsilon=1)

f_density_grid_num=35 f_density_grid_width=10.0

computing ./data_parameter/player_gaussin_fit/grid_full/e1_player10_gaussin_prob_grid.pkl
computation is done in 44.65061283111572 seconds
dump_pickle to ./data_parameter/player_gaussin_fit/grid_full/e1_player10_gaussin_prob_grid.pkl

computing ./data_parameter/player_gaussin_fit/grid_full/e1_playert_gaussin_prob_grid.pkl
computation is done in 44.10276913642883 seconds
dump_pickle to ./data_parameter/player_gaussin_fit/grid_full/e1_playert_gaussin_prob_grid.pkl


{'prob_grid_singlescore': array([[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],
 
        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],
 
        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],
 
        ...,
 
        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0

In [4]:
playerID_list = [10]
fgag.save_aiming_grid_custom_no_tokens(playerID_list)
fgag.save_aiming_grid_custom_tokens(playerID_list)
fgag.save_aiming_grid_custom_only_tokens(playerID_list)

generate and save action set grid_version=custom_no_tokens
load_pickle from ./data_parameter/player_gaussin_fit/grid_full/e1_player10_gaussin_prob_grid.pkl
load_pickle from ./data_parameter/player_gaussin_fit/grid_full/e1_playert_gaussin_prob_grid.pkl
dump_pickle to ./data_parameter/player_gaussin_fit/grid_custom_no_tokens/player10_gaussin_prob_grid_custom_no_tokens.pkl

generate and save action set grid_version=custom_tokens
load_pickle from ./data_parameter/player_gaussin_fit/grid_full/e1_player10_gaussin_prob_grid.pkl
dump_pickle to ./data_parameter/player_gaussin_fit/grid_custom_tokens/player10_gaussin_prob_grid_custom_tokens.pkl

generate and save action set grid_version=custom_only_tokens
load_pickle from ./data_parameter/player_gaussin_fit/grid_full/e1_playert_gaussin_prob_grid.pkl
dump_pickle to ./data_parameter/player_gaussin_fit/grid_custom_only_tokens/player10_gaussin_prob_grid_custom_only_tokens.pkl



In [5]:
grid_version = 'custom_tokens'
name_pa = 'player{}'.format(10)
postfix=''
gpu_device = None ## Using CPU
  
[aiming_grid, prob_grid_normalscore, prob_grid_singlescore, prob_grid_doublescore, prob_grid_triplescore, prob_grid_bullscore] = fgag.load_aiming_grid(name_pa, data_parameter_dir=data_parameter_dir, grid_version=grid_version)
    
res1 = function_solve_dp.solve_singlegame(name_pa, data_parameter_dir=data_parameter_dir, grid_version=grid_version, result_dir=result_dir, postfix=postfix, gpu_device=gpu_device)


load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_tokens/player10_gaussin_prob_grid_custom_tokens.pkl
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_tokens/player10_gaussin_prob_grid_custom_tokens.pkl
runing solve_dp_turn


/Users/rachael/Desktop/darts-thesis/function_solve_dp.py:80: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/darts-thesis/function_solve_dp.py:347: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[:,score_gained_index] = num_turns_array[:,score_gained_index] / prob_notbust_dic[score_max]
/Users/rachael/Desktop/darts-thesis/function_solve_dp.py:360: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()
/Users/rachael/Desktop/darts-thesis/function_solve_dp.py:360: RuntimeWarning: invalid value encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()


solve prob_policy_transit in 0.2307429313659668 seconds
solve dp_turn_policyiter in 1.5716321468353271 seconds
[0. 0. 1. ... 3. 3. 3.]
dump_pickle to ./result/singlegame_player10_turn_custom_tokens.pkl


In [3]:
grid_version = 'custom_tokens'
name_pa = 'player{}'.format(10)
postfix=''
gpu_device = None ## Using CPU
  
[aiming_grid, prob_grid_normalscore, prob_grid_singlescore, prob_grid_doublescore, prob_grid_triplescore, prob_grid_bullscore] = fgag.load_aiming_grid(name_pa, data_parameter_dir=data_parameter_dir, grid_version=grid_version)
    
res1 = function_solve_dp.solve_singlegame(name_pa, data_parameter_dir=data_parameter_dir, grid_version=grid_version, result_dir=result_dir, postfix=postfix, gpu_device=gpu_device)


load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_tokens/player10_gaussin_prob_grid_custom_tokens.pkl
load_pickle from ./data_parameter/player_gaussin_fit/grid_custom_tokens/player10_gaussin_prob_grid_custom_tokens.pkl
runing solve_dp_turn


/Users/rachael/Desktop/OptimalDarts-main/function_solve_dp.py:80: RuntimeWarning: divide by zero encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/OptimalDarts-main/function_solve_dp.py:80: RuntimeWarning: overflow encountered in divide
  num_tothrow = num_tothrow / prob_otherstate
/Users/rachael/Desktop/OptimalDarts-main/function_solve_dp.py:347: RuntimeWarning: divide by zero encountered in divide
  num_turns_array[:,score_gained_index] = num_turns_array[:,score_gained_index] / prob_notbust_dic[score_max]
/Users/rachael/Desktop/OptimalDarts-main/function_solve_dp.py:347: RuntimeWarning: overflow encountered in divide
  num_turns_array[:,score_gained_index] = num_turns_array[:,score_gained_index] / prob_notbust_dic[score_max]
/Users/rachael/Desktop/OptimalDarts-main/function_solve_dp.py:360: RuntimeWarning: divide by zero encountered in divide
  value_relerror[rt] = np.abs((state_value_update[rt] - state_value[rt])/state_value_update[rt]).max()

solve prob_policy_transit in 0.24202799797058105 seconds
solve dp_turn_policyiter in 2.4333739280700684 seconds
[0. 0. 1. ... 3. 3. 3.]
dump_pickle to ./result/singlegame_player10_turn_custom_tokens.pkl


In [14]:
res = ft.load_pickle('result/singlegame_player10_turn_custom_tokens.pkl', encoding='latin1', printflag=False)

In [7]:
res.keys()

dict_keys(['optimal_value_dic', 'optimal_action_index_dic', 'optimal_value_rt3', 'prob_scorestate_transit'])

In [15]:
res['optimal_action_index_dic']

{2: [None,
  array([56, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
         -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], dtype=int32),
  array([54, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], dtype=int32),
  array([54], dtype=int32)],
 3: [None,
  array([40, 55, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,

In [11]:
a_throw_list[11]

'T20-c-i'

In [17]:
res['optimal_value_rt3']

array([0.    , 0.    , 1.4381, ..., 3.9892, 3.9464, 3.9783])